name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: TestJob
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'
        env:
          NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --filter Category!=it --no-restore --verbosity normal
      - name: Pack
        run: dotnet pack --no-build --configuration Release ./src/Goncolos/Goncolos.csproj --output .
      - name: Push Nuget
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.PUBLISH_TO_NUGET_ORG }} --skip-duplicate